server:
  port: 8080
spring:
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/FE/
  #      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/hyperlogy_ban_hang_2
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        hbm2ddl:
          auto: update
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
#      spring.mvc.view.prefix: /WEB-INF/view/
#spring.mvc.view.suffix: .jspa
